Feature/map component
hotosm/imagery-requests pull request #42
Opened 2016-12-08 20:34 UTC by nbumbarger

Adds functional map to the map placeholder, and connects it to the API to visualize the collection of requests (in the home view), individual requests (in the requests view), a user's requests (in the dashboard view), and individual tasks (in the task view).

2016-12-09 21:57 UTC, nbumbarger commented
This is ready. Most views include the view map, and the task page temporarily contains an example of the edit component.

2016-12-12 21:07 UTC, danielfdsilva requested changes
Other notes:
- Please add the token to `production.js` This is not sensitive and unless we go with a different map, won't change. (update the readme to reflect this)

2016-12-12 21:07 UTC, danielfdsilva commented on app/assets/scripts/components/display-map.js
> +    mapClass: T.string
Better to use `className` so it's a common property.

2016-12-12 21:07 UTC, danielfdsilva commented on app/assets/scripts/components/display-map.js
> +    mapboxgl.accessToken = config.mbToken;
move to `main.js` so we only do it once across the site. No need for duplication.

2016-12-12 21:07 UTC, danielfdsilva commented on app/assets/scripts/components/edit-map.js
> +  displayName: 'DisplayMap',
Wrong `displayName`

2016-12-12 21:07 UTC, danielfdsilva commented on app/assets/scripts/components/edit-map.js
> +    mapClass: T.string
Better to use `className` so it's a common property.

2016-12-12 21:07 UTC, danielfdsilva commented on app/index.html
> +    <link rel="stylesheet" href="/node_modules/mapbox-gl-draw/dist/mapbox-gl-draw.css">
These need to be included in the build process above (line 43-45).

2016-12-12 22:40 UTC, danielfdsilva requested changes

2016-12-12 22:40 UTC, danielfdsilva commented on README.md
> +  mbToken: 'pk.eyJ1I...'
Since this is in the `production.js` which is committed, we can remove it from here

2016-12-12 22:40 UTC, danielfdsilva commented on app/index.html
> +    <link rel="stylesheet" href="/node_modules/mapbox-gl/dist/mapbox-gl.css">
This was actually my bad.
Can we move these 2 to the vendor build? lines 40-41

2016-12-13 15:41 UTC, danielfdsilva approved these changes

2016-12-13 15:42 UTC, merged