Add task stats to user dashboard
hotosm/imagery-requests pull request #56
Opened 2016-12-20 17:13 UTC by danielfdsilva

2016-12-20 17:58 UTC, nbumbarger requested changes
- As the surveyor, I changed the status of two requests from "completed" to "in progress". They're now labeled as "in progress," but the stats still show 0 active, 2 completed.
- I think that submitting a change to a task status should return the user to their previous view, or at least give some indication that the input was received.

2016-12-20 17:58 UTC, nbumbarger commented on app/assets/scripts/views/dashboard.js
> +          <li className='stats-list__item'><strong>{data.stats.completedTasks}</strong>completed</li>
this returns undefined; it needs to reference `data.stats.completeTasks`

2016-12-21 17:57 UTC, danielfdsilva commented on app/assets/scripts/views/dashboard.js
> +          <li className='stats-list__item'><strong>{data.stats.completedTasks}</strong>completed</li>
This was my bad. I made a change to ensure consistent naming but forgot to push :S
Here it is: https://github.com/hotosm/imagery-requests-api/pull/16

2016-12-21 18:10 UTC, danielfdsilva commented
@nbumbarger 
1) Where are you seeing those statuses?
2) When you submit a task status change it immediately appears below the form. What do you mean by return to the previous view?

2016-12-22 19:37 UTC, nbumbarger commented
@danielfdsilva

1. The stat mismatch is visible in the dashboard- closing a task, then reopening it, doesn't update the number of open/ closed tasks displayed at the top of the page.
2. This isn't a real issue, but I think there should be more visual feedback when adding comments. It's hard to notice the addition. Maybe an animation that slides the comments down to make room?

2016-12-22 19:37 UTC, merged